-- nos conectamos como administradores
ALTER TRIGGER ctrl_borrado DISABLE;
DROP TABLE control_borrado;
CREATE TABLE control_borrado (
usuario VARCHAR2(50),
momento TIMESTAMP,
objeto VARCHAR2(50));


CREATE OR REPLACE TRIGGER ctrl_borrado
BEFORE DROP
ON database
BEGIN
	INSERT INTO control_borrado VALUES(ORA_LOGIN_USER,SYSTIMESTAMP,ORA_DICT_OBJ_NAME);
END;
/




select * from control_borrado;



CREATE TABLE KK (kk NUMBER(1));
CREATE TABLE KK1 (kk NUMBER(1));
CREATE TABLE KK2 (kk NUMBER(1));
CREATE TABLE KK3 (kk NUMBER(1));
CREATE TABLE KK4 (kk NUMBER(1));
CREATE TABLE KK5 (kk NUMBER(1));
CREATE TABLE KK6 (kk NUMBER(1));
CREATE TABLE KK7 (kk NUMBER(1));
CREATE TABLE KK8 (kk NUMBER(1));
CREATE TABLE KK9 (kk NUMBER(1));
CREATE TABLE KK10 (kk NUMBER(1));
CREATE TABLE KK11 (kk NUMBER(1));
CREATE TABLE KK12 (kk NUMBER(1));

DROP TABLE KK;
DROP TABLE KK1;
DROP TABLE KK2;
DROP TABLE KK3;
DROP TABLE KK4;
DROP TABLE KK5;
DROP TABLE KK6;
DROP TABLE KK7;
DROP TABLE KK8;
DROP TABLE KK9;
DROP TABLE KK10;
DROP TABLE KK11;
DROP TABLE KK12;